title: Paolo Brasolin
description: Paolo Brasolin

compress_html:
  comments: ["<!-- ", " -->"]

exclude:
  - "Makefile"
  - "_tailwind/"
  - ".ruby-gemset"
  - "Gemfile"
  - "Gemfile.lock"
  - "node_modules/"
  - "yarn.lock"
  - "postcss.config.js"
  - "tailwind.config.js"
  - "package.json"
  - "favicon.ico"
